### ISSUE TITLE
Enhancement: Script + Background Audio

### ISSUE THREAD

**Issue by joemidi** [google-marketing-solutions/ariel#14]
I'm trying to use this on a project but I don't want to use my source audio - I want a fresh new track.

I should be able to supply just the Script and the Background Music and it would create what I need.

But the current set up - I have to supply separate Vocals and Music which doesn't really make sense to me.

**Comment by kacpersh** [comment]
This is resolved now in 0.0.25.

Please specify your audio track in `audio_google_drive_link` under `Dubbing configuration - advanced`
